### ISSUE TITLE
Continue this project, please

### ISSUE THREAD

**Issue by Jelly9912** [PocketMineDevelopers/SurvivalGames#12]
Don't leave :/

**Comment by Creeperface01** [comment]
Don't worry :) i will but now im too busy

**Comment by Jelly9912** [comment]
I have a sugestion, when player join to the arena, spawn a particle effect  on player position or y+2, it looks nice :)
Particles are awesome :D

**Comment by Driesboy** [comment]
Dont leave

**Comment by Creeperface01** [comment]
Hm ok :)

**Comment by Driesboy** [comment]
Thanks

**Comment by Driesboy** [comment]
Ok but i need a hg plugin 
Please

**Comment by majovec** [comment]
Skoda ze ten plugin nereaguje na comandy jinak by to byl super plugin

**Comment by Jelly9912** [comment]
Majovec, are yoy from poland?

**Comment by majovec** [comment]
no Czech Republick

**Comment by Creeperface01** [comment]
bude reagovat ale nevím momentálně pracujeme na annihilation a bedwars
Annihilation: play.minetox.cz:27579
BedWars: play.minetox.cz:19132

**Comment by majovec** [comment]
ano to vim ze delate to anni a bw jen je skoda ze je mala pravdepodobnost se dotat na bw a kort si tam zahrat a kdyz si zrovna zahraju tak chytnu bug ze mi nejde vubec obchodova -,-  ale snad si ten ca najdes na spraveni toho sg jelikoz to je neco co se da aspon sehnat ne jak to bw ktery se neda sehnat a kdyz se sezene tak neni dodelany  ale jinak diky za odpoved

**Comment by kvetinac97** [comment]
Ohledně BW: Připojit se můžeš pokud si koupis VIP+ko a výš(79 Kč na měsíc není moc) Pokud ti nefunguje shop tak na channelu bit.do/YTkvetinac je návod na obchodování ve Windows 10 Edition, v MCPE možná ještě udělám

**Comment by majovec** [comment]
hmm mam android ale pokazde chytnu ten takzvany bug ze si nakoupim vsechno v pohode  v inventu veci mam ale pak kdyz na ne kliknu veci zmizi a to uz  sem mel vse nakoupeno i ty cihly zmizi a  vip si koupit tak to vrazim mesicne za server na ktery prestyly lidi chodit skoda 15 slotu kort kdz je zaplacen na 90 dni jeste ale to je vedlejsi a prave proto bych byl rad kdyby se vam podarilo dokoncit to SG abych aspon zkuil nejako nalakat lidi

**Comment by Ragnok123** [comment]
No lakanim nic nedosahnes. Aby chodili na sg, musi byt rewardy. Budou tady rewardy, ale na popularnich serverech jsou rewardy jako tokeny, coz musi sg navazan na nejaky core. Stejnak tento plugin asi bude zverejnen pro vsechny.

**Comment by majovec** [comment]
Hele Olegu to mas pravdu hele precti si mail neco sem ti tam poslal

**Comment by Ragnok123** [comment]
Do pharu to das pres devtools. Nebo web :). Jinak nepochopil jsem te s configama. Ten tvuj beta-plugin (myslim ze je podarenej) ani nepotrebuje configy

**Comment by majovec** [comment]
a myslel sem to takto ze skoro jikdo kdo ma server od FH nechodi na github

**Comment by Ragnok123** [comment]
Na fh neni mcpe popularni. Github je spis "code-sharing"

**Comment by majovec** [comment]
hmm posledni dobou ta popularita fakaheda MCPE serveru opada jak snih ze strechy a odpovez pls na mail
