### ISSUE TITLE
Is it Mcrafters old place

### ISSUE THREAD

**Issue by CraftingMania** [PocketMineDevelopers/SurvivalGames#14]
??????

**Comment by Creeperface01** [comment]
I think better would be make this minigame fkr nukkit

**Comment by CraftingMania** [comment]
github.com/mcrafterss

**Comment by Creeperface01** [comment]
What do you mean?  :D

**Comment by CraftingMania** [comment]
kevinatic team is mcrafters and i am on it wanna join

**Comment by CraftingMania** [comment]
taha is on it too

**Comment by kvetinac97** [comment]
This is not MCrafters old repository. MCrafters has been MCrafters since start
