### ISSUE TITLE
Help me :(

### ISSUE THREAD

**Issue by Taytan9912** [PocketMineDevelopers/SurvivalGames#4]
[PocketMine] Server is starting...
[PocketMine] Server was started.
[Server] [18:32:55] [Server thread/WARNING]: Timezone could not be automatically determined. An incorrect timezone will result in incorrect timestamps on console logs. It has been set to "UTC" by default. You can change it on the php.ini file.
[Server] [18:32:55] [Server thread/INFO]: Loading pocketmine.yml...
[Server] [18:32:55] [Server thread/INFO]: Loading server properties...
[Server] [18:32:55] [Server thread/INFO]: Selected English (eng) as the base language
[Server] [18:32:55] [Server thread/INFO]: Starting Minecraft: PE server version v0.12.1 alpha
[Server] [18:32:55] [Server thread/INFO]: Opening server on 0.0.0.0:19132
[Server] [18:32:55] [Server thread/INFO]: This server is running PocketMine-MP version 1.6dev-28 "[REDACTED]" (API 1.13.0)
[Server] [18:32:55] [Server thread/INFO]: PocketMine-MP is distributed under the LGPL License
[Server] [18:32:56] [Server thread/INFO]: Loading ManyWorlds v2.0.2
[Server] [18:32:56] [Server thread/INFO]: Loading DevTools v1.10.0
[Server] [18:32:56] [Server thread/INFO]: Loading ZipPluginLoader v1.1.2
[Server] [18:32:56] [Server thread/INFO]: Enabling DevTools v1.10.0
[Server] [18:32:56] [Server thread/INFO]: Loading source plugin BugFix v1.0.0
[Server] [18:32:56] [Server thread/INFO]: Loading source plugin SurvivalGamesPE v0.0.1.beta
[Server] [18:32:56] [Server thread/INFO]: Loading source plugin SimpleOtu v1.0.0
[Server] [18:32:56] [Server thread/INFO]: [DevTools] Registered folder plugin loader
[Server] [18:32:56] [Server thread/INFO]: Enabling ZipPluginLoader v1.1.2
[Server] [18:32:56] [Server thread/INFO]: Enabling SurvivalGamesPE v0.0.1.beta
[Server] [18:32:56] [Server thread/INFO]: Selected language English
[Server] [18:32:56] [Server thread/INFO]: [SurvivalGamesPE] checking arena files...
[Server] 
[Server] Fatal error: Class name must be a valid object or a string in phar:///storage/emulated/0/PocketMine/PocketMine-MP.phar/src/pocketmine/Server__32bit.php on line 1135
[Server] [18:32:56] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
[Server] [18:32:56] [Server thread/EMERGENCY]: Please upload the "/storage/emulated/0/PocketMine/CrashDump_Fri_Sep_18-18.32.56-UTC_2015.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.
[Server] [18:33:03] [Server thread/INFO]: Disabling DevTools v1.10.0
[Server] [18:33:03] [Server thread/INFO]: Disabling ZipPluginLoader v1.1.2
[Server] [18:33:03] [Server thread/INFO]: Disabling SurvivalGamesPE v0.0.1.beta

So... what i can do ?

**Comment by kvetinac97** [comment]
How you can?! see, SurvivalGames is in-development. Check the page https://github.com/PocketMineDevelopers/SurvivalGames/updates/ for beta and development/stable builds. For now, there is NO STABLE/BETA/DEVELOPMENT build.

**Comment by Taytan9912** [comment]
404 page not found

**Comment by kvetinac97** [comment]
That's no build yet. This is reason why: "404 PAGE NOT FOUND"

**Comment by Taytan9912** [comment]
Ok, my bad, so sorry :/
