### ISSUE TITLE
Commands Don't work.

### ISSUE THREAD

**Issue by MrGamerPro** [PocketMineDevelopers/SurvivalGames#8]
I do /sg and it doesn't do any thing :-1:  Please give a better example of how to use this.

**Comment by Taytan9912** [comment]
This is not done yet, please wait for release ;)

**Comment by kvetinac97** [comment]
<font color="red">Please note that this is something like "live-development" and it isn't DONE yet. </font>

**Comment by MrGamerPro** [comment]
Will this be released on the pocketmine site?

**Comment by kvetinac97** [comment]
Yes

**Comment by Creeperface01** [comment]
some beta builds will be released here
