### ISSUE TITLE
Plsko

### ISSUE THREAD

**Issue by ondraczsk** [PocketMineDevelopers/SurvivalGames#9]
Můžu bejt v  tomto týmu? Udělal bych reklamu na mem serveru nebo něco jsem velkej fanda květináče

PS.: Květináči dáš mi tvůj skype?

**Comment by Creeperface01** [comment]
Pokud umíš PHP tak ano

**Comment by ondraczsk** [comment]
no a co bych dělal
mužu dát jazyk no slovenštiny..

**Comment by Creeperface01** [comment]
No to taky můžeš

**Comment by ondraczsk** [comment]
ok juknu se na to
dáte mě na to do toho plugins.yml jako ze sem to přeložil?

**Comment by Creeperface01** [comment]
Ne ale budeš tady vidět

**Comment by ondraczsk** [comment]
ok

**Comment by Creeperface01** [comment]
pokud to přeložíš tak bude vidět že si to přeložil ty a taky pak bude napsané na fóru nebo někde kdo co přeložil
